1. Install the Transformers library.
2. Load the pre-trained T5 model and the associated tokenizer.
3. Prepare your dataset: tokenize the inputs and the labels.
4. Train the model on your dataset.
5. Evaluate the model on your validation set.

In [1]:
import torch
torch.cuda.empty_cache()

In [ ]:
!pip install simplet5

In [3]:
from simplet5 import SimpleT5

2024-02-09 22:45:59.352742: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-02-09 22:45:59.352833: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-02-09 22:45:59.473293: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered

In [4]:
model = SimpleT5()
model.from_pretrained("t5","t5-base")

Downloading:   0%|          | 0.00/773k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.32M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.18k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/850M [00:00<?, ?B/s]

In [5]:
import pandas as pd

In [6]:
train_df = pd.read_csv("/kaggle/input/trainingdata/trainingdata.csv")
train_df.head()

,source_text,target_text
0,US consumer spending dropped by a record in Ap...,consumer spending plunges 13.6 percent in Apri...
1,State-run lenders require an urgent Rs 1.2 tri...,government will have to take a bulk of the tab...
2,Apparel exporters on Wednesday urged the gover...,exporters are facing issues in terms of raw ma...
3,Asian shares battled to extend a global reboun...,the dollar loses some ground on the safe haven...
4,After Indiaâ€™s sovereign credit rating fell t...,six Indian public-sector undertakings have tak...

In [7]:
train_df['source_text'][4]

'After Indiaâ€™s sovereign credit rating fell to lowest investment grade â€˜Baa3â€™ early in June, six Indian public-sector undertakings (PSUs) have also taken a hit with them now becoming potential â€œfallen angelsâ€\x9d. These six companies in the non-financial sector viz â€” Indian Oil Corporation, Hindustan Petroleum Corporation, Oil India, Petronet LNG, Bharat Petroleum Corporation and Oil and Natural Gas Corporation â€” are now just one step away from being considered junk, global ratings agency Moodyâ€™s Investors Service said on Tuesday. â€œFallen Angelsâ€\x9d are those companies which were earlier in the investment grade category and have slipped to sub-investment grade.\n\nAs the coronavirus pandemic has afflicted markets and economy around the world, the Asian list of potential â€œfallen angelsâ€\x9d has reached an all time high of 21 in early June owing to the addition of six Indian PSUs, the agency said. The quantum of names in the list has doubled due to the COVID-19 pandemic. The 21 Asian companies, which now risk becoming fallen angels, have over $12.3 billion of outstanding bonds maturing in 2021. Of this $12.3 billion, about one-fourth at $3.3 billion are rated. The six Indian companies which have been added to the potential â€œfallen angelsâ€\x9d category are state-run enterprises in the oil and gas sector. They have $1 billion of rated bonds coming up for repayment till 2021, the agency said.\n\nIndia leaves China behind, but, that is no good news\n\nSince 2008, Chinese companies have dominated the â€œfallen angelsâ€\x9d list which has lately become a domain of Indian and South Korean companies.\n\nMoodyâ€™s downgraded its rating on India by a notch recently after worries over growth and the fiscal strain abound. Indiaâ€™s current rating is the last level in the category classified as â€œinvestment gradeâ€\x9d. â€œThe countryâ€™s policymaking institutions will be challenged in enacting and implementing policies which effectively mitigate the risks of a sustained period of relatively low growth, significant further deterioration in the general government fiscal position and stress in the financial sector,â€\x9d Moodyâ€™s said in a statement after downgrading India rating. However, the effect of the cut is likely to be short term on investment flows.'

In [8]:
# changing all values to string type
train_df['source_text'] = train_df['source_text'].astype(str)
# replacing \n by ''
train_df['source_text'] = train_df['source_text'].str.replace('\n','')
# removing garbage characters using regex
train_df['source_text'] = train_df['source_text'].str.replace(r'[^a-zA-Z0-9\s.,-]', '', regex=True)
train_df['source_text'][4]

'After Indias sovereign credit rating fell to lowest investment grade Baa3 early in June, six Indian public-sector undertakings PSUs have also taken a hit with them now becoming potential fallen angels. These six companies in the non-financial sector viz  Indian Oil Corporation, Hindustan Petroleum Corporation, Oil India, Petronet LNG, Bharat Petroleum Corporation and Oil and Natural Gas Corporation  are now just one step away from being considered junk, global ratings agency Moodys Investors Service said on Tuesday. Fallen Angels are those companies which were earlier in the investment grade category and have slipped to sub-investment grade.As the coronavirus pandemic has afflicted markets and economy around the world, the Asian list of potential fallen angels has reached an all time high of 21 in early June owing to the addition of six Indian PSUs, the agency said. The quantum of names in the list has doubled due to the COVID-19 pandemic. The 21 Asian companies, which now risk becoming fallen angels, have over 12.3 billion of outstanding bonds maturing in 2021. Of this 12.3 billion, about one-fourth at 3.3 billion are rated. The six Indian companies which have been added to the potential fallen angels category are state-run enterprises in the oil and gas sector. They have 1 billion of rated bonds coming up for repayment till 2021, the agency said.India leaves China behind, but, that is no good newsSince 2008, Chinese companies have dominated the fallen angels list which has lately become a domain of Indian and South Korean companies.Moodys downgraded its rating on India by a notch recently after worries over growth and the fiscal strain abound. Indias current rating is the last level in the category classified as investment grade. The countrys policymaking institutions will be challenged in enacting and implementing policies which effectively mitigate the risks of a sustained period of relatively low growth, significant further deterioration in the general government fiscal position and stress in the financial sector, Moodys said in a statement after downgrading India rating. However, the effect of the cut is likely to be short term on investment flows.'

In [9]:
# changing all values to string type
train_df['target_text'] = train_df['target_text'].astype(str)

In [10]:
train_df['target_text'][0]

'consumer spending plunges 13.6 percent in April. that was the biggest drop since the government started tracking series in 1959. consumer spending accounts for more than two-thirds of economic activity. economists polled by Reuters had forecast consumer spending plummeting 12.6 percent. a spokesman for the u.s. government said the data was not available.'

In [11]:
# changing first word of each sentence to upper case
train_df['target_text'] = train_df['target_text'].apply(lambda x: '. '.join(sentence[0].upper()+sentence[1:] for sentence in x.split('. ') if sentence!=''))
train_df['target_text'][0]

'Consumer spending plunges 13.6 percent in April. That was the biggest drop since the government started tracking series in 1959. Consumer spending accounts for more than two-thirds of economic activity. Economists polled by Reuters had forecast consumer spending plummeting 12.6 percent. A spokesman for the u.s. Government said the data was not available.'

In [12]:
train_df.head()

,source_text,target_text
0,US consumer spending dropped by a record in Ap...,Consumer spending plunges 13.6 percent in Apri...
1,State-run lenders require an urgent Rs 1.2 tri...,Government will have to take a bulk of the tab...
2,Apparel exporters on Wednesday urged the gover...,Exporters are facing issues in terms of raw ma...
3,Asian shares battled to extend a global reboun...,The dollar loses some ground on the safe haven...
4,After Indias sovereign credit rating fell to l...,Six Indian public-sector undertakings have tak...

In [13]:
# load train_df to datasetdict
from datasets import Dataset, DatasetDict
dataset = Dataset.from_pandas(train_df)
dataset = DatasetDict({'train': dataset})
dataset

DatasetDict({
    train: Dataset({
        features: ['source_text', 'target_text'],
        num_rows: 33365
    })
})

In [14]:
# split the data into train and test
from sklearn.model_selection import train_test_split
splitted_data = dataset['train'].train_test_split(test_size=0.2)
dataset = DatasetDict({
    'train': splitted_data['train'],
    'test': splitted_data['test']
})

In [ ]:
!pip install transformers

In [16]:
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("t5-base")

In [17]:
tokenizer("Hello, this one sentence!")

{'input_ids': [8774, 6, 48, 80, 7142, 55, 1], 'attention_mask': [1, 1, 1, 1, 1, 1, 1]}

In [18]:
tokenizer(["Hello, this one sentence!", "This is another sentence."])

{'input_ids': [[8774, 6, 48, 80, 7142, 55, 1], [100, 19, 430, 7142, 5, 1]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1]]}

In [19]:
with tokenizer.as_target_tokenizer():
    print(tokenizer(["Hello, this one sentence!", "This is another sentence."]))

{'input_ids': [[8774, 6, 48, 80, 7142, 55, 1], [100, 19, 430, 7142, 5, 1]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1]]}

In [20]:
prefix = "summarize: "

In [21]:
max_input_length = 1024
max_target_length = 128

def preprocess_function(examples):
    inputs = [prefix + doc for doc in examples["source_text"]]
    model_inputs = tokenizer(inputs, max_length=max_input_length, truncation=True)

    # Setup the tokenizer for targets
    with tokenizer.as_target_tokenizer():
        labels = tokenizer(examples["target_text"], max_length=max_target_length, truncation=True)

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

In [22]:
preprocess_function(dataset['train'][:2])

{'input_ids': [[21603, 10, 619, 3, 115, 7, 15, 619, 29, 7, 15, 619, 14816, 1960, 7, 301, 566, 1537, 419, 9928, 565, 18080, 3937, 391, 3502, 11636, 11, 3, 16143, 2578, 8530, 4159, 7735, 107, 736, 3478, 23, 30, 2083, 489, 243, 419, 9928, 565, 7802, 32, 65, 582, 8, 2015, 12024, 16, 8, 1125, 628, 16, 1244, 20008, 5, 134, 14661, 53, 44, 8, 1360, 20008, 3699, 1769, 12968, 6, 736, 3478, 23, 243, 20008, 47, 8, 3, 2935, 26, 109, 13, 2913, 2121, 16, 1547, 147, 3, 9, 2646, 977, 5, 852, 6, 8, 97, 65, 369, 21, 39, 538, 12, 582, 3, 9, 2488, 12, 8, 21670, 9199, 12197, 5, 683, 23, 32, 141, 3, 10671, 91, 296, 18, 4057, 3620, 28, 20043, 13, 2950, 364, 12, 199, 3607, 9284, 13, 8, 2896, 13, 8, 21670, 9199, 12197, 6, 736, 3478, 23, 243, 5, 8123, 3478, 23, 12566, 24, 419, 9928, 2319, 1729, 13, 11715, 204, 16235, 23095, 16, 1244, 20008, 3744, 12, 81, 80, 18, 324, 189, 13, 8, 975, 24422, 6203, 792, 7686, 16, 1547, 78, 623, 5, 391, 3502, 7, 1729, 16, 8, 538, 47, 11715, 6464, 2560, 23095, 16, 5123, 3, 88, 243, 5, 683, 23, 32, 65, 2932, 582, 8, 2015, 12024, 16, 8, 1125, 628, 16, 48, 538, 6, 3, 88, 974, 5, 37, 391, 3502, 11636, 243, 8, 975, 24422, 342, 19, 1459, 12, 856, 4032, 147, 11715, 13923, 23095, 5, 8123, 3478, 23, 2162, 24, 910, 1093, 13, 8, 2315, 2074, 19, 952, 12, 36, 2303, 28, 8, 7802, 32, 1229, 57, 8, 414, 13, 4144, 188, 40, 7, 32, 608, 4043, 5027, 4159, 7735, 107, 736, 3478, 23, 845, 1547, 56, 582, 220, 52, 26, 2015, 2717, 28, 3, 9, 11284, 13, 147, 335, 20179, 3809, 7802, 32, 6, 1125, 23071, 23, 106, 13, 5372, 3212, 19, 3, 9, 5734, 5, 7802, 32, 65, 885, 12, 209, 27880, 1676, 1769, 12790, 640, 20008, 5, 852, 6, 16, 780, 430, 775, 6121, 6, 62, 43, 356, 95, 7802, 32, 4564, 7, 38, 3, 9, 1223, 3438, 4245, 16, 1659, 5372, 3212, 6, 12, 11226, 12, 8, 1710, 5372, 512, 11, 284, 11, 334, 3309, 16, 1244, 20008, 6, 3, 88, 243, 5, 15013, 175, 7802, 32, 4564, 7, 6, 62, 56, 43, 7944, 11, 23812, 3053, 16, 334, 3, 17, 15, 107, 7, 173, 13, 8, 538, 12, 1716, 334, 712, 3309, 5, 282, 62, 2516, 469, 6, 10239, 7802, 32, 4564, 7, 33, 641, 7763, 11, 62, 56, 2387, 3, 9, 11668, 57, 8, 414, 13, 8, 215, 6, 3, 88, 974, 5, 308, 159, 15085, 49, 419, 9928, 565, 18080, 3937, 6, 84, 293, 7, 7802, 32, 6, 19, 8, 4199, 27483, 13, 14092, 3159, 5313, 84, 7415, 3426, 2606, 3159, 9682, 7, 3937, 5, 1], [21603, 10, 11808, 3, 15349, 1547, 30, 2089, 3759, 4136, 981, 1275, 28, 46, 2674, 12, 16, 11656, 884, 3410, 11, 482, 3, 9, 1465, 6493, 16, 8, 512, 1083, 14495, 53, 365, 8, 1113, 13, 2684, 3035, 11, 4301, 106, 9, 18095, 18, 14515, 6081, 3035, 5, 5110, 588, 165, 16675, 2689, 6864, 6, 8, 2968, 3873, 443, 8337, 19, 1772, 3, 30853, 981, 1275, 379, 150, 3, 25284, 21, 166, 386, 767, 6, 18605, 3, 25284, 7, 21, 8, 166, 1296, 767, 28, 1646, 3, 25284, 7, 1684, 45, 489, 189, 847, 13, 1242, 11, 9445, 1201, 4760, 2289, 5, 188, 7, 8, 3212, 640, 8, 684, 456, 3, 60, 8751, 53, 11, 2673, 1731, 16, 3, 9, 2769, 26, 3107, 6, 62, 33, 3, 13505, 16675, 2689, 6864, 6, 3, 9, 2290, 13, 3, 30853, 11, 1385, 4136, 981, 1275, 6, 3, 8287, 44, 3, 60, 7417, 53, 884, 3410, 11, 3, 23988, 135, 12, 805, 70, 11808, 6, 11808, 18, 15349, 1547, 3, 16143, 2578, 11, 4071, 3394, 9430, 29, 157, 243, 16, 3, 9, 2493, 5, 3845, 856, 243, 6, 16675, 2689, 6864, 19, 1385, 4136, 11, 62, 33, 4881, 56, 16, 11656, 884, 3410, 57, 326, 19966, 128, 13, 70, 981, 3148, 7, 5, 506, 2592, 8621, 1275, 33, 80, 18, 858, 18, 7085, 773, 11, 33, 69, 293, 194, 13, 3956, 69, 722, 7686, 11, 3, 14198, 8, 22519, 512, 2428, 5, 5911, 7765, 308, 4481, 3, 31334, 15, 3, 31349, 282, 5100, 14218, 4197, 72, 571, 405, 3, 9, 12956, 161, 71, 12956, 930, 57, 22336, 1765, 3, 9, 793, 7952, 5, 71, 12956, 59, 163, 21151, 7, 9392, 1773, 12, 1822, 151, 45, 136, 647, 2847, 7765, 308, 4481, 7952, 6, 68, 92, 1691, 1224, 918, 160, 26, 26510, 12, 474, 46, 414, 12, 8, 2131, 221, 3113, 5, 1347, 26, 26510, 6986, 116, 3, 9, 6684, 5294, 13, 3, 9, 2074, 2992, 9392, 12, 3, 9, 1994, 6, 492, 8, 3060, 13, 1994, 45, 568, 12, 568, 9909, 5, 37, 207, 1506, 19, 24, 180, 25210, 18, 3881, 553, 4949, 6722, 65, 118, 5163, 5711, 6, 84, 5386, 8, 5931, 2020, 13, 3, 9, 12956, 5, 571, 186, 1308, 13, 12956, 7, 33, 132, 290, 33, 23971, 662, 1308, 13, 12956, 80, 6, 3, 9, 12956, 3, 390, 30, 8, 829, 6722, 48, 228, 36, 893, 16, 8463, 920, 6, 42, 46, 44, 324, 76, 920, 3, 31315, 6722, 12956, 192, 6, 3, 9, 529, 18, 60, 10435, 1014, 16686, 12938, 12956, 24, 2284, 3, 9, 31144, 6722, 38, 12938, 24, 3, 11078, 8, 1181, 729, 13, 180, 25210, 18, 3881, 553, 386, 6, 206, 2482, 447, 18, 9, 10812, 12956, 7, 24, 43, 6472, 1037, 114, 6642, 11, 3, 11840, 13, 1181, 729, 7, 114, 22440, 3619, 787, 12, 3, 9, 568, 6, 2022, 936, 2640, 20, 4978, 6472, 1037, 11, 1759, 8, 12956, 11, 662, 6, 3619, 769, 15129, 12956, 213, 77, 8, 3, 60, 9763, 77, 288, 13167, 13, 180, 25210, 18, 5911, 553, 4949, 590, 28, 46, 19181, 76, 6451, 22205, 19, 787, 38, 3, 9, 12956, 5, 363, 405, 34, 240, 12, 1344, 3, 9, 12956, 13, 48, 773, 3, 31334, 15, 606, 19, 3, 9, 307, 6, 1561, 433, 5, 3, 8739, 4845, 24, 33, 787, 12, 151, 28, 3, 9, 1994, 26, 6, 12956, 7, 33, 787, 12, 1695, 151, 11, 92, 9930, 6795, 224, 38, 502, 6, 9841, 887, 11, 8, 12766, 5, 264, 17577, 3830, 33, 29701, 5, 5528, 845, 24, 8, 10391, 97, 34, 808, 12, 1344, 3, 9, 12956, 19, 874, 203, 6, 68, 34, 1086, 1217, 1486, 42, 1664, 12063, 24, 97, 5, 4197, 72, 3111, 13026, 106, 9, 18095, 1547, 3529, 301, 8087, 6130, 7, 5110, 588, 16675, 2689, 6864, 3, 9, 884, 3882, 53, 21, 3, 9, 1068, 2289, 54, 17671, 13, 46, 3, 25284, 339, 1059, 21, 8, 166, 386, 767, 11, 3718, 20345, 7, 56, 163, 9158, 227, 386, 767, 13, 8, 6180, 6464, 305, 203, 2289, 38, 3, 30853, 5, 188, 40, 7, 32, 6, 8, 349, 19, 1260, 5021, 18, 11161, 6503, 1182, 6, 365, 84, 3, 9, 884, 54, 726, 422, 4505, 38, 3, 25284, 7, 21, 8, 166, 1296, 767, 13, 8, 1696, 11, 1646, 3, 25284, 7, 1684, 45, 8, 17353, 847, 5, 18180, 15, 1395, 18, 15349, 1547, 92, 243, 3, 99, 19, 1772, 21, 8, 166, 97, 664, 3, 9, 9445, 1201, 2289, 20752, 28, 8, 884, 92, 578, 8, 1182, 12, 3882, 21, 3, 9, 7206, 805, 223, 227, 874, 203, 5, 5890, 297, 53, 30, 268, 3, 60, 4078, 102, 1575, 826, 12633, 13, 6081, 3035, 5749, 6, 9430, 29, 157, 243, 6, 101, 33, 18642, 120, 652, 223, 12, 268, 28, 26079, 3, 60, 18, 8751, 53, 13, 69, 17603, 7, 640, 3212, 826, 66, 8, 569, 1028, 17, 9, 4733, 18870, 11, 21186, 49, 53, 12, 66, 1455, 11, 3, 7, 152, 155, 2121, 3629, 5, 101, 33, 4881, 6, 62, 56, 36, 3, 179, 12, 7763, 159, 15, 8, 4080, 14290, 826, 8, 415, 5779, 21130, 7, 6, 1116, 5, 371, 32, 40, 3216, 69, 423, 2591, 13, 8, 4301, 106, 9, 18095, 2131, 221, 3113, 270, 5, 1]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], 'labels': [[4159, 7735, 107, 736, 3478, 23, 243, 4653, 20008, 47, 3, 31, 2935, 26, 109, 13, 2913, 2121, 31, 16, 18222, 5, 216, 243, 8, 538, 19, 230, 3, 9, 2488, 12, 8, 4509, 2913, 9481, 5, 216, 243, 8, 975, 24422, 342, 19, 1459, 12, 4032, 147, 11715, 13923, 23095, 5, 216, 243, 910, 1093, 13, 8, 538, 31, 7, 2074, 19, 952, 12, 36, 2303, 28, 8, 1229, 57, 8, 414, 13, 4144, 1], [11808, 3, 15349, 1547, 30, 2089, 3759, 4136, 981, 1275, 5, 37, 1669, 19, 1772, 3, 30853, 981, 1275, 379, 150, 3, 25284, 21, 166, 386, 767, 6, 18605, 3, 25284, 7, 21, 8, 166, 1296, 767, 11, 1646, 3, 25284, 7, 1684, 45, 489, 189, 847, 13, 1242, 5, 37, 888, 19, 3, 8287, 44, 16, 11656, 53, 884, 3410, 11, 1577, 3, 9, 1465, 6493, 16, 8, 512, 1083, 14495, 53, 365, 8, 1113, 13, 2684, 3035, 11, 4301, 106, 9, 18095, 18, 14515, 6081, 3035, 5, 1]]}

In [23]:
tokenized_datasets = dataset.map(preprocess_function, batched=True)

  0%|          | 0/27 [00:00<?, ?ba/s]

  0%|          | 0/7 [00:00<?, ?ba/s]

In [24]:
from transformers import AutoModelForSeq2SeqLM, DataCollatorForSeq2Seq, Seq2SeqTrainingArguments, Seq2SeqTrainer
model = AutoModelForSeq2SeqLM.from_pretrained("t5-base")

In [25]:
batch_size = 4
args = Seq2SeqTrainingArguments(
    "test-summarization",
    evaluation_strategy = "epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=batch_size,
    per_device_eval_batch_size=batch_size,
    weight_decay=0.01,
    save_total_limit=3,
    num_train_epochs=1,
    predict_with_generate=True,
    fp16=True,
)

In [26]:
data_collator = DataCollatorForSeq2Seq(tokenizer, model=model)

In [ ]:
!pip install rouge_score

In [28]:
from datasets import load_metric
metric = load_metric("rouge")

Downloading builder script:   0%|          | 0.00/2.16k [00:00<?, ?B/s]

In [29]:
import nltk
import numpy as np

def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    decoded_preds = tokenizer.batch_decode(predictions, skip_special_tokens=True)
    # Replace -100 in the labels as we can't decode them.
    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
    decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)

    # Rouge expects a newline after each sentence
    decoded_preds = ["\n".join(nltk.sent_tokenize(pred.strip())) for pred in decoded_preds]
    decoded_labels = ["\n".join(nltk.sent_tokenize(label.strip())) for label in decoded_labels]

    result = metric.compute(predictions=decoded_preds, references=decoded_labels, use_stemmer=True)
    # Extract a few results
    result = {key: value.mid.fmeasure * 100 for key, value in result.items()}

    # Add mean generated length
    prediction_lens = [np.count_nonzero(pred != tokenizer.pad_token_id) for pred in predictions]
    result["gen_len"] = np.mean(prediction_lens)

    return {k: round(v, 4) for k, v in result.items()}

In [30]:
trainer = Seq2SeqTrainer(
    model,
    args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["test"],
    data_collator=data_collator,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics
)

Using amp half precision backend

In [31]:
trainer.train()

The following columns in the training set  don't have a corresponding argument in `T5ForConditionalGeneration.forward` and have been ignored: source_text, target_text.
/opt/conda/lib/python3.10/site-packages/transformers/optimization.py:306: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use thePyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
***** Running training *****
  Num examples = 26692
  Num Epochs = 1
  Instantaneous batch size per device = 4
  Total train batch size (w. parallel, distributed & accumulation) = 4
  Gradient Accumulation steps = 1
  Total optimization steps = 6673
Automatic Weights & Biases logging enabled, to disable set os.environ["WANDB_DISABLED"] = "true"
wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize
wandb: Paste an API key from your profile and hit enter, or press ctrl+c to quit:

  ········································

wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc

Saving model checkpoint to test-summarization/checkpoint-500
Configuration saved in test-summarization/checkpoint-500/config.json
Model weights saved in test-summarization/checkpoint-500/pytorch_model.bin
tokenizer config file saved in test-summarization/checkpoint-500/tokenizer_config.json
Special tokens file saved in test-summarization/checkpoint-500/special_tokens_map.json
Copy vocab file to test-summarization/checkpoint-500/spiece.model
Saving model checkpoint to test-summarization/checkpoint-1000
Configuration saved in test-summarization/checkpoint-1000/config.json
Model weights saved in test-summarization/checkpoint-1000/pytorch_model.bin
tokenizer config file saved in test-summarization/checkpoint-1000/tokenizer_config.json
Special tokens file saved in test-summarization/checkpoint-1000/special_tokens_map.json
Copy vocab file to test-summarization/checkpoint-1000/spiece.model
Saving model checkpoint to test-summarization/checkpoint-1500
Configuration saved in test-summarization/checkpoint-1500/config.json
Model weights saved in test-summarization/checkpoint-1500/pytorch_model.bin
tokenizer config file saved in test-summarization/checkpoint-1500/tokenizer_config.json
Special tokens file saved in test-summarization/checkpoint-1500/special_tokens_map.json
Copy vocab file to test-summarization/checkpoint-1500/spiece.model
Saving model checkpoint to test-summarization/checkpoint-2000
Configuration saved in test-summarization/checkpoint-2000/config.json
Model weights saved in test-summarization/checkpoint-2000/pytorch_model.bin
tokenizer config file saved in test-summarization/checkpoint-2000/tokenizer_config.json
Special tokens file saved in test-summarization/checkpoint-2000/special_tokens_map.json
Copy vocab file to test-summarization/checkpoint-2000/spiece.model
Deleting older checkpoint [test-summarization/checkpoint-500] due to args.save_total_limit
Saving model checkpoint to test-summarization/checkpoint-2500
Configuration saved in test-summarization/checkpoint-2500/config.json
Model weights saved in test-summarization/checkpoint-2500/pytorch_model.bin
tokenizer config file saved in test-summarization/checkpoint-2500/tokenizer_config.json
Special tokens file saved in test-summarization/checkpoint-2500/special_tokens_map.json
Copy vocab file to test-summarization/checkpoint-2500/spiece.model
Deleting older checkpoint [test-summarization/checkpoint-1000] due to args.save_total_limit
Saving model checkpoint to test-summarization/checkpoint-3000
Configuration saved in test-summarization/checkpoint-3000/config.json
Model weights saved in test-summarization/checkpoint-3000/pytorch_model.bin
tokenizer config file saved in test-summarization/checkpoint-3000/tokenizer_config.json
Special tokens file saved in test-summarization/checkpoint-3000/special_tokens_map.json
Copy vocab file to test-summarization/checkpoint-3000/spiece.model
Deleting older checkpoint [test-summarization/checkpoint-1500] due to args.save_total_limit
Saving model checkpoint to test-summarization/checkpoint-3500
Configuration saved in test-summarization/checkpoint-3500/config.json
Model weights saved in test-summarization/checkpoint-3500/pytorch_model.bin
tokenizer config file saved in test-summarization/checkpoint-3500/tokenizer_config.json
Special tokens file saved in test-summarization/checkpoint-3500/special_tokens_map.json
Copy vocab file to test-summarization/checkpoint-3500/spiece.model
Deleting older checkpoint [test-summarization/checkpoint-2000] due to args.save_total_limit
Saving model checkpoint to test-summarization/checkpoint-4000
Configuration saved in test-summarization/checkpoint-4000/config.json
Model weights saved in test-summarization/checkpoint-4000/pytorch_model.bin
tokenizer config file saved in test-summarization/checkpoint-4000/tokenizer_config.json
Special tokens file saved in test-summarization/checkpoint-4000/special_tokens_map.json
Copy vocab file to test-summarization/checkpoint-4000/spiece.model
Deleting older checkpoint [test-summarization/checkpoint-2500] due to args.save_total_limit
Saving model checkpoint to test-summarization/checkpoint-4500
Configuration saved in test-summarization/checkpoint-4500/config.json
Model weights saved in test-summarization/checkpoint-4500/pytorch_model.bin
tokenizer config file saved in test-summarization/checkpoint-4500/tokenizer_config.json
Special tokens file saved in test-summarization/checkpoint-4500/special_tokens_map.json
Copy vocab file to test-summarization/checkpoint-4500/spiece.model
Deleting older checkpoint [test-summarization/checkpoint-3000] due to args.save_total_limit
Saving model checkpoint to test-summarization/checkpoint-5000
Configuration saved in test-summarization/checkpoint-5000/config.json
Model weights saved in test-summarization/checkpoint-5000/pytorch_model.bin
tokenizer config file saved in test-summarization/checkpoint-5000/tokenizer_config.json
Special tokens file saved in test-summarization/checkpoint-5000/special_tokens_map.json
Copy vocab file to test-summarization/checkpoint-5000/spiece.model
Deleting older checkpoint [test-summarization/checkpoint-3500] due to args.save_total_limit
Saving model checkpoint to test-summarization/checkpoint-5500
Configuration saved in test-summarization/checkpoint-5500/config.json
Model weights saved in test-summarization/checkpoint-5500/pytorch_model.bin
tokenizer config file saved in test-summarization/checkpoint-5500/tokenizer_config.json
Special tokens file saved in test-summarization/checkpoint-5500/special_tokens_map.json
Copy vocab file to test-summarization/checkpoint-5500/spiece.model
Deleting older checkpoint [test-summarization/checkpoint-4000] due to args.save_total_limit
Saving model checkpoint to test-summarization/checkpoint-6000
Configuration saved in test-summarization/checkpoint-6000/config.json
Model weights saved in test-summarization/checkpoint-6000/pytorch_model.bin
tokenizer config file saved in test-summarization/checkpoint-6000/tokenizer_config.json
Special tokens file saved in test-summarization/checkpoint-6000/special_tokens_map.json
Copy vocab file to test-summarization/checkpoint-6000/spiece.model
Deleting older checkpoint [test-summarization/checkpoint-4500] due to args.save_total_limit
Saving model checkpoint to test-summarization/checkpoint-6500
Configuration saved in test-summarization/checkpoint-6500/config.json
Model weights saved in test-summarization/checkpoint-6500/pytorch_model.bin
tokenizer config file saved in test-summarization/checkpoint-6500/tokenizer_config.json
Special tokens file saved in test-summarization/checkpoint-6500/special_tokens_map.json
Copy vocab file to test-summarization/checkpoint-6500/spiece.model
Deleting older checkpoint [test-summarization/checkpoint-5000] due to args.save_total_limit
The following columns in the evaluation set  don't have a corresponding argument in `T5ForConditionalGeneration.forward` and have been ignored: source_text, target_text.
***** Running Evaluation *****
  Num examples = 6673
  Batch size = 4


Training completed. Do not forget to share your model on huggingface.co/models =)

TrainOutput(global_step=6673, training_loss=0.6216298976116732, metrics={'train_runtime': 6255.6124, 'train_samples_per_second': 4.267, 'train_steps_per_second': 1.067, 'total_flos': 2.905564552077312e+16, 'train_loss': 0.6216298976116732, 'epoch': 1.0})

In [34]:
# save the finetuned model
trainer.save_model("t5-base-finetuned")

Saving model checkpoint to t5-base-finetuned
Configuration saved in t5-base-finetuned/config.json
Model weights saved in t5-base-finetuned/pytorch_model.bin
tokenizer config file saved in t5-base-finetuned/tokenizer_config.json
Special tokens file saved in t5-base-finetuned/special_tokens_map.json
Copy vocab file to t5-base-finetuned/spiece.model

In [35]:
from transformers import T5ForConditionalGeneration, T5Tokenizer

# Load the saved model and tokenizer
model = T5ForConditionalGeneration.from_pretrained('/kaggle/working/t5-base-finetuned')
tokenizer = T5Tokenizer.from_pretrained('/kaggle/working/t5-base-finetuned')

# Prepare your input data
input_text = "After more than two weeks of testimony, the jury at the coroner's inquest into the stabbing massacre at James Smith Cree Nation shared its recommendations to help prevent similar tragedies in the future. The inquest, which began on Jan. 15 in Melfort, Sask., has been examining the events of Sept. 4, 2022, when Myles Sanderson killed 11 people — 10 from James Smith and one from the neighbouring village of Weldon. During the past two weeks, jurors have heard from 30 witnesses including RCMP officers, a psychologist, forensic pathologists, Sanderson's former partner, officials from the Parole Board of Canada and the elders who worked with Sanderson in prison."
inputs = tokenizer(input_text, return_tensors='pt')

# Generate predictions
outputs = model.generate(inputs['input_ids'])

# Decode the predictions
predicted_text = tokenizer.decode(outputs[0], skip_special_tokens=True)
predicted_text

loading configuration file /kaggle/working/t5-base-finetuned/config.json
Model config T5Config {
  "_name_or_path": "t5-base",
  "architectures": [
    "T5ForConditionalGeneration"
  ],
  "d_ff": 3072,
  "d_kv": 64,
  "d_model": 768,
  "decoder_start_token_id": 0,
  "dropout_rate": 0.1,
  "eos_token_id": 1,
  "feed_forward_proj": "relu",
  "initializer_factor": 1.0,
  "is_encoder_decoder": true,
  "layer_norm_epsilon": 1e-06,
  "model_type": "t5",
  "n_positions": 512,
  "num_decoder_layers": 12,
  "num_heads": 12,
  "num_layers": 12,
  "output_past": true,
  "pad_token_id": 0,
  "relative_attention_num_buckets": 32,
  "task_specific_params": {
    "summarization": {
      "early_stopping": true,
      "length_penalty": 2.0,
      "max_length": 200,
      "min_length": 30,
      "no_repeat_ngram_size": 3,
      "num_beams": 4,
      "prefix": "summarize: "
    },
    "translation_en_to_de": {
      "early_stopping": true,
      "max_length": 300,
      "num_beams": 4,
      "prefix": "translate English to German: "
    },
    "translation_en_to_fr": {
      "early_stopping": true,
      "max_length": 300,
      "num_beams": 4,
      "prefix": "translate English to French: "
    },
    "translation_en_to_ro": {
      "early_stopping": true,
      "max_length": 300,
      "num_beams": 4,
      "prefix": "translate English to Romanian: "
    }
  },
  "torch_dtype": "float32",
  "transformers_version": "4.16.2",
  "use_cache": true,
  "vocab_size": 32128
}

loading weights file /kaggle/working/t5-base-finetuned/pytorch_model.bin
All model checkpoint weights were used when initializing T5ForConditionalGeneration.

All the weights of T5ForConditionalGeneration were initialized from the model checkpoint at /kaggle/working/t5-base-finetuned.
If your task is similar to the task the model of the checkpoint was trained on, you can already use T5ForConditionalGeneration for predictions without further training.
Didn't find file /kaggle/working/t5-base-finetuned/added_tokens.json. We won't load it.
loading file /kaggle/working/t5-base-finetuned/spiece.model
loading file None
loading file /kaggle/working/t5-base-finetuned/special_tokens_map.json
loading file /kaggle/working/t5-base-finetuned/tokenizer_config.json
loading file /kaggle/working/t5-base-finetuned/tokenizer.json

"The jury at the coroner's inquest into the stabbing massacre at James"